//  ----------------------------------------------------------------------------------
//  Copyright Microsoft Corporation
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//  ----------------------------------------------------------------------------------

namespace DurableTask.Core.History
{
    using System.Runtime.Serialization;

    /// <summary>
    /// Generic History event
    /// </summary>
    [DataContract]
    public class ExecutionRewoundEvent : HistoryEvent
    {
        /// <summary>
        /// The reason for the rewind event.
        /// </summary>
        [DataMember] public string Reason;

        /// <summary>
        /// The new execution ID of the rewound orchestration. If none is provided, a new ID will be generated by the orchestration itself.
        /// </summary>
        [DataMember] public string NewExecutionId;

        /// <summary>
        /// Creates a new ExecutionRewoundEvent with the supplied event id and reason.
        /// </summary>
        /// <param name="eventId">The integer event id</param>
        /// <param name="reason">The reason for the rewind event</param>
        public ExecutionRewoundEvent(int eventId, string reason)
            : base(eventId)
        {
            this.Reason = reason;
        }

        /// <summary>
        /// Gets the event type
        /// </summary>
        public override EventType EventType => EventType.ExecutionRewound;
    }
}