parameters:
- name: buildConfiguration
  displayName: Build Configuration
  type: string
  default: Debug
  values:
  - Debug
  - Release

pr:
  branches:
    include:
    - main
trigger: none

jobs:
- job: Validate
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core 3.1'
    inputs:
      packageType: 'sdk'
      version: '3.1.x'

  - task: UseDotNet@2
    displayName: 'Install Latest .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '7.x'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: DurableTask.sln
      arguments: '-c ${{ parameters.buildConfiguration }} -p:ContinuousIntegrationBuild=true'

  - task: Npm@1
    displayName: 'Install Azurite'
    inputs:
      command: custom
      customCommand: 'install -g azurite'

  - bash: |
     azurite --silent --location $(Agent.TempDirectory)/azurite &
     echo "##vso[task.setvariable variable=azuritePid]$!"
    displayName: 'Start Azurite'

  - task: VSTest@3
    displayName: 'Run unit and functional tests'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\test\DurableTask.AzureStorage.Tests\bin\${{ parameters.buildConfiguration }}\**\DurableTask.AzureStorage.Tests.dll
        **\test\DurableTask.Core.Tests\bin\${{ parameters.buildConfiguration }}\**\DurableTask.Core.Tests.dll
        !**\obj\**
      testFiltercriteria: 'TestCategory!=DisabledInCI'
      distributionBatchType: basedOnExecutionTime
      configuration: ${{ parameters.buildConfiguration }}
      diagnosticsEnabled: True
      collectDumpOn: always
      rerunFailedTests: true
      rerunFailedThreshold: 20
      rerunMaxAttempts: 2
    env:
      DurableTaskTestStorageConnectionString: UseDevelopmentStorage=true
  
  - bash: kill $(azuritePid)
    displayName: 'Stop Azurite'
    condition: always()
