jobs:
  -job: SignAndPublish
   displayName: Sign & Publish

   steps:
    - template: ci/sign-files.yml@eng
      parameters:
        displayName: Sign assemblies
        folderPath: src
        pattern: DurableTask.*.dll
        signType: dll
    
    - task: DotNetCoreCLI@2
      displayName: Generate nuget packages
      inputs:
        command: pack
        verbosityPack: Minimal
        configuration: Release
        nobuild: true
        packDirectory: $(build.artifactStagingDirectory)
        packagesToPack: 'src/DurableTask.AzureStorage/DurableTask.AzureStorage.sln'

    - task: DotNetCoreCLI@2
      displayName: Generate nuget packages
      inputs:
        command: pack
        verbosityPack: Minimal
        configuration: Release
        nobuild: true
        packDirectory: $(build.artifactStagingDirectory)
        packagesToPack: 'src/DurableTask.ApplicationInsights/DurableTask.ApplicationInsights.csproj'

    - template: ci/sign-files.yml@eng
      parameters:
        displayName: Sign NugetPackages
        folderPath: $(build.artifactStagingDirectory)
        pattern: '*.nupkg'
        signType: nuget