trigger:
  branches:
    include:
    # These are the branches we'll mirror to our internal ADO instance
    # Keep this set limited as appropriate (don't mirror individual user branches).
    - main

resources:
  repositories:
  - repository: eng
    type: git
    name: engineering
    ref: refs/tags/release

variables:
  - template: ci/variables/cfs.yml@eng

extends:
  template: ci/code-mirror.yml@eng
