# This build is used for public PR and CI builds.

# Run on pushes to main
trigger:
  batch: true
  branches:
    include:
    - main

# Run nightly to catch new CVEs and to report SDL often.
schedules:
  - cron: "0 0 * * *"
    displayName: Nightly Run
    branches:
      include:
      - main
    always: true # Always run pipeline irrespective of changes since the last successful scheduled run; default is false

# Run on all PRs
pr:
  branches:
    include:
    - '*'

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows

    sdl:
      codeql:
        compiled:
          enabled: true
        runSourceLanguagesInSourceAnalysis: true

    settings:
      # PR's from forks should not have permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
    - stage: Build & Test
      jobs:
      - template: /eng/ci/templates/build.yml@self # TODO: This also signs, refactor signing step out for speed
      - template: /eng/ci/templates/test.yml@self