<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildThisFileDirectory),DurableTask.sln))\tools\DurableTask.props" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net472;net48</TargetFrameworks>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\DurableTask.Core\DurableTask.Core.csproj" />
  </ItemGroup>

</Project>